<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.7.0" />
    <PackageReference Include="Codeer.LowCode.Bindings.Blazor-ApexCharts.Designer" Version="0.25.3" />
    <PackageReference Include="Codeer.LowCode.Blazor.Extras.Designer" Version="0.8.1" />
    <PackageReference Include="System.Net.Http.WinHttpHandler" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.1.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" />
    <PackageReference Include="Codeer.LowCode.Blazor.Designer.Standard" Version="0.8.5" />
    <PackageReference Include="Codeer.LowCode.Blazor.Designer" Version="1.3.25" />
    <ProjectReference Include="..\LowCodeApp.Client.Shared\LowCodeApp.Client.Shared.csproj" />
    <PackageReference Include="Codeer.LowCode.Blazor.DbAccess" Version="0.1.0" />
  </ItemGroup>
</Project>